name: base
channels:
  - defaults
dependencies:
  - conda
  - python=3.9
  - conda-env
  - conda-build
  - conda-verify
  - _ipyw_jlab_nb_ext_conf
  - anaconda==2021.11=py39_0
  - anaconda-navigator
  - navigator-updater
  - seaborn
  - shapprefix: /home/nacho/anaconda3
